version: "3.8"
services:
  testDbContainer:
    image: postgres:alpine
    restart: always
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: testPass
    volumes:
      - ./init-user-db.sql:/docker-entrypoint-initdb.d/user.sql
